import { ServiceProviders } from "@/app_modules/types/services.providers";

export const fakeProviders: ServiceProviders[] = [
  {
    uid: "1",
    jobType: "Electrician",
    jobId: "electrician",
    profile: "Electrician Expert",
    user: {
      username: "john_doe",
      fullname: "John Doe",
      email: "john@example.com",
      password: "",
      NIN: "123456789",
      photo: "https://i.pravatar.cc/100?img=1",
      createdAt: "",
      updated: "",
      passwordChangedAt: "",
      recentPasswords: [],
      userId: "user1",
      balance: 100,
      balance_before: 90,
      balance_updatedAt: "",
    },
    currentProviderLocation: [6.5244, 3.3792],
  },
  {
    uid: "2",
    jobType: "Plumber",
    jobId: "plumber",
    profile: "Plumbing Services",
    user: {
      username: "jane_doe",
      fullname: "Jane Doe",
      email: "jane@example.com",
      password: "",
      NIN: "987654321",
      photo: "https://i.pravatar.cc/100?img=2",
      createdAt: "",
      updated: "",
      passwordChangedAt: "",
      recentPasswords: [],
      userId: "user2",
      balance: 120,
      balance_before: 100,
      balance_updatedAt: "",
    },
    currentProviderLocation: [6.5244, 3.3792],
  },
];
